// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbnYedOw-tUJTgHI6XMw8xnWQc9C-_1sI',
    appId: '1:741267383047:web:8998ed8f378bbf48701ba2',
    messagingSenderId: '741267383047',
    projectId: 'studenthelper-79c48',
    authDomain: 'studenthelper-79c48.firebaseapp.com',
    storageBucket: 'studenthelper-79c48.appspot.com',
    measurementId: 'G-6LY2BN6PRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKhZcP0sLW6hGUArvjg2wbiMC_xpDxHVM',
    appId: '1:741267383047:android:dfb4d7580095ab29701ba2',
    messagingSenderId: '741267383047',
    projectId: 'studenthelper-79c48',
    storageBucket: 'studenthelper-79c48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB5HP7EwAez3jLDe_r7xb6_3CU3gwr1r0',
    appId: '1:741267383047:ios:0342a30fccc291d2701ba2',
    messagingSenderId: '741267383047',
    projectId: 'studenthelper-79c48',
    storageBucket: 'studenthelper-79c48.appspot.com',
    iosClientId: '741267383047-qaflp957s0414nibsfdck5npkvik58u6.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentHelper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB5HP7EwAez3jLDe_r7xb6_3CU3gwr1r0',
    appId: '1:741267383047:ios:0342a30fccc291d2701ba2',
    messagingSenderId: '741267383047',
    projectId: 'studenthelper-79c48',
    storageBucket: 'studenthelper-79c48.appspot.com',
    iosClientId: '741267383047-qaflp957s0414nibsfdck5npkvik58u6.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentHelper',
  );
}
